name = "nexu-router"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[services]]
binding = "LANDING"
service = "nexu-landing-worker"

[[services]]
binding = "APP"
service = "nexu-app-worker"

[vars]
API_ORIGIN = "https://api.nexu.io"
